// NOTE to use this you'll need to install REST CLIENT vscode extension
@baseUrl = http://localhost:5000/api
@json = application/json
@refreshToken = {{accessTokens.response.body.tokens.refreshToken}}
@accessToken = {{accessTokens.response.body.tokens.accessToken}}

@password = {{loginCredentials.password}}
@username

### Create account
# @name loginCredentials
POST {{baseUrl}}/users/signup
Content-Type: {{json}}

{
    "firstName": "Gabriel",
    "lastName":"Ezekiel-Hart",
    "username": "gabby",
    "password": "password"
}
### Login to a user account
# @name accessTokens
POST {{baseUrl}}/users/login
Content-Type: {{json}}

{
    "username":"slick",
    "password":"paul92702689"
}

### Logout of the accout
POST {{baseUrl}}/users/logout
RefreshToken: Bearer {{refreshToken}}
Authorization: Bearer {{accessToken}}

### Get authenticated user's profile data
GET {{baseUrl}}/users/me
Authorization:Bearer {{accessToken}}

### Generate Access token with refreshtoken
# @name accessTokens
GET {{baseUrl}}/users/createaccess
RefreshToken: Bearer {{refreshToken}}

### create quotes
POST {{baseUrl}}/quotes/create
Authorization: Bearer {{accessToken}}
Content-Type: {{json}}

{
    "title": "We live to Die",
    "quote": "Life is nothing but a place to preper for death!"
}
### get all my quotes
GET {{baseUrl}}/quotes/me
Authorization: Bearer {{accessToken}}
Content-Type: {{json}}

###
GET {{baseUrl}}/610bb69bb20480655a93b35b/quotes


###
POST {{baseUrl}}/quotes/reaction/610bd21061829c0d17410946?like=true
Authorization: Bearer {{accessToken}}