// NOTE to use this you'll need to install REST CLIENT vscode extension
@url = http://localhost:5000/api
@contentType = application/json
@refreshToken = {{login.response.body.tokens.refreshToken}}
@accessToken = {{access.response.body.tokens.accessToken}}

### Create account
POST {{url}}/users/signup
Content-Type: application/json

{
    "firstName": "Mike",
    "lastName":"Jubily",
    "username": "jubliks",
    "password": "jubily"
}
### Login
# @name login
POST {{url}}/users/login
Content-Type: application/json

{
    "username":"jubliks",
    "password":"jubily"
}

### Logout of the accout
POST {{url}}/users/logout
RefreshToken: Bearer {{refreshToken}}
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users/me
Authorization:Bearer {{accessToken}}

### Generate Access token with refreshtoken
# @name access
GET {{url}}/users/createaccess
RefreshToken: Bearer {{refreshToken}}

### create quotes
POST {{url}}/quotes/create
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
    "title": "We live to Die",
    "quote": "Life is nothing but a place to preper for death!"
}
### get all my quotes
GET {{url}}/quotes/me
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

###
GET {{url}}/610bb69bb20480655a93b35b/quotes


###
POST {{url}}/quotes/reaction/610bd21061829c0d17410946?like=true
Authorization: Bearer {{accessToken}}